version: "3.8"

networks:
  ms-network:
    name: ms-network

services:
  eureka-server:
    image: dineshdontha67/eureka-server:latest
    ports:
    - "8761:8761"
    networks:
      - ms-network
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  microservice2:
    image: dineshdontha67/microservice2:latest
    ports:
    - "8082:8082"
    networks:
      - ms-network
    depends_on:
      - eureka-server
    environment:
      server.port: 8082
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka


#EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka
#    networks:
#      - ms-network
#    depends_on:
#      - eureka-server
#      server.port: 8082
#      eureka.host: eureka-server
#      eureka.client.enabled: 'true'
#      eureka.instance.preferIpAddress: 'true'
